name: inputs demo
on:
    workflow_dispatch:
        inputs:
            name:
                description: "enter your name"
                required: true
                default: "sai"
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print Inputs
              run: | 
                echo "Name: ${{ inputs.name }}"
